modLoader="javafml" #mandatory
loaderVersion="[27,)" #mandatory (24 is current forge version)
credits="This mod is made possible by Harry Talks, Ankix, Cadiboo." #optional
authors="Crazzy4999" #optional

[[mods]] #mandatory
modId="betterbiomesmodbycrazzy" #mandatory
version="0.1.0" #mandatory
displayName="Better Biomes Mod" #mandatory
description='''
this mod adds lots of new biomes to the game.
Also lots of new blocks, trees, structures and items the game.
'''

[[dependencies.betterbiomesmodbycrazzy]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[27,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.betterbiomesmodbycrazzy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3]"
    ordering="NONE"
    side="BOTH"